/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Java_Swing_Project;

import java.awt.event.MouseEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;



/**
 *
 * @author W10
 */
public class Table extends javax.swing.JFrame {

    private ArrayList<Student> eleves;
    private DefaultTableModel model;//if i want to work with liste or Table, i have to create Table Model
    // "model" is responsible for displaying information in the Table
    //i can create My table headers like that :
    String [] NameColonne = {"Name", "Note 1", "Note 2", "Note 3", "Average"};
    public Table() {
        initComponents();
        eleves= new ArrayList();
        model = new DefaultTableModel(NameColonne,0);// 0 Because i don't want to craete Eny "colonne" In Beginning
        table.setModel(model); // Link between table and model
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        note2 = new javax.swing.JLabel();
        note1 = new javax.swing.JLabel();
        name = new javax.swing.JLabel();
        note3 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt1 = new javax.swing.JTextField();
        btnmodifier = new javax.swing.JButton();
        btnsupprimer = new javax.swing.JButton();
        btnquiter = new javax.swing.JButton();
        bntajouter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 300));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Note 1", "Note 2", "Note 3", "Moyenne "
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setResizable(false);
            table.getColumnModel().getColumn(1).setResizable(false);
            table.getColumnModel().getColumn(2).setResizable(false);
            table.getColumnModel().getColumn(3).setResizable(false);
            table.getColumnModel().getColumn(4).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 450, 90));

        note2.setBackground(new java.awt.Color(255, 255, 255));
        note2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        note2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        note2.setText("Note 2 :");
        getContentPane().add(note2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, 80, 40));

        note1.setBackground(new java.awt.Color(255, 255, 255));
        note1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        note1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        note1.setText("Note 1 :");
        getContentPane().add(note1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, 80, 40));

        name.setBackground(new java.awt.Color(255, 255, 255));
        name.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        name.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        name.setText("Name   :");
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 80, 40));

        note3.setBackground(new java.awt.Color(255, 255, 255));
        note3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        note3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        note3.setText("Note 3 :");
        getContentPane().add(note3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 80, 40));

        txt2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        getContentPane().add(txt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 180, 40));

        txt3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt3ActionPerformed(evt);
            }
        });
        getContentPane().add(txt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 180, 40));

        txt4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        getContentPane().add(txt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 180, 40));

        txt1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        getContentPane().add(txt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 180, 40));

        btnmodifier.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnmodifier.setText("Modification");
        btnmodifier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmodifierActionPerformed(evt);
            }
        });
        getContentPane().add(btnmodifier, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 150, 40));

        btnsupprimer.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnsupprimer.setText("Delete");
        btnsupprimer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsupprimerActionPerformed(evt);
            }
        });
        getContentPane().add(btnsupprimer, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 160, 150, 40));

        btnquiter.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btnquiter.setText("Exit");
        btnquiter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnquiterActionPerformed(evt);
            }
        });
        getContentPane().add(btnquiter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 220, 150, 40));

        bntajouter.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        bntajouter.setText("Add");
        bntajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntajouterActionPerformed(evt);
            }
        });
        getContentPane().add(bntajouter, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 40, 150, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnquiterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnquiterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnquiterActionPerformed
        private void Erase()
        {
            txt1.setText("");
            txt2.setText("");
            txt3.setText("");
            txt4.setText("");
            txt1.requestFocus();
        }
    private void bntajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntajouterActionPerformed
     if(txt1.getText().isEmpty()||txt2.getText().isEmpty()||txt3.getText().isEmpty()||txt4.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Fill in the Fields", "Empty fields", JOptionPane.OK_OPTION);
     }
     else{  
        String Name;
        float note1,note2,note3,moyenne;    
        Name = txt1.getText();
        note1 = Float.valueOf(txt2.getText()) ;
        note2 = Float.valueOf(txt3.getText()) ;
        note3 = Float.valueOf(txt4.getText()) ;
        moyenne = (note1+note2+note3)/3 ;//Float.parseFloat(String.format("%.2f", (note1+note2+note3)/3 ));
        
        // I don't want to repeat the same person
        boolean eleveExistant = false;
        
     for(int i=0;i<eleves.size();i++)
     {
        Student eleve = eleves.get(i);
        if(Name.equals(eleve.getName()))
        {
            eleveExistant = true;
        }
     }
     if(eleveExistant)
     {
        JOptionPane.showMessageDialog(this,"student already existing", "Duplication", JOptionPane.ERROR_MESSAGE);
     }
     else
     {
        Student s = new Student(Name, note1, note2, note3, moyenne);
        eleves.add(s);
        //put My "eleve" inside Model
        model.insertRow(model.getRowCount(), new Object[]{ //getRowCount return -1 if i don't select enything
        Name,note1,note2,note3,moyenne
     });
     }
     Erase();
    
     }
    }//GEN-LAST:event_bntajouterActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        txt2.requestFocus();
    }//GEN-LAST:event_txt1ActionPerformed

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        txt3.requestFocus();
    }//GEN-LAST:event_txt2ActionPerformed

    private void txt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt3ActionPerformed
        txt4.requestFocus();
    }//GEN-LAST:event_txt3ActionPerformed

    private void btnsupprimerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsupprimerActionPerformed
        int indice = table.getSelectedRow();//getSelectedRow return -1 if i don't select enything
        if(indice != -1)
        {
            eleves.remove(indice);
            model.removeRow(indice);
            Erase();
        }
        else
        {
            JOptionPane.showMessageDialog(this, "Please choose a student", "Not Selected item", WIDTH);
        }
    }//GEN-LAST:event_btnsupprimerActionPerformed

    private void tableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableMouseClicked
        if(evt.getButton()== MouseEvent.BUTTON1)
        {
            int indice = table.getSelectedRow();
            if(indice!= -1)
            {
                txt1.setText(model.getValueAt(indice, 0).toString());
                txt2.setText(model.getValueAt(indice, 1).toString());
                txt3.setText(model.getValueAt(indice, 2).toString());
                txt4.setText(model.getValueAt(indice, 3).toString());
            }
            else if(evt.getButton()== MouseEvent.BUTTON3)
            {
                Erase();
                table.clearSelection();
            }
        }
    }//GEN-LAST:event_tableMouseClicked

    private void btnmodifierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmodifierActionPerformed
        if(txt1.getText().isEmpty()||txt2.getText().isEmpty()||txt3.getText().isEmpty()||txt4.getText().isEmpty()){
        JOptionPane.showMessageDialog(this, "Fill in the Fields", "Empty fields", JOptionPane.OK_OPTION);
        }
        else
        {
        int indice = table.getSelectedRow();//getSelectedRow return -1 if i don't select enything
        if(indice != -1)
        {
        String Name;
        float note1,note2,note3,moyenne;    
           Name = txt1.getText();
           note1 = Float.valueOf(txt2.getText()) ;
           note2 = Float.valueOf(txt3.getText()) ;
           note3 = Float.valueOf(txt4.getText()) ;
           moyenne = (note1+note2+note3)/3;
           
           Student s = eleves.get(indice);
           s.setName(Name);
           s.setNote1(note1);
           s.setNote2(note2);
           s.setNote3(note3);
           s.setMoyenne(moyenne);
           model.setValueAt(Name, indice, 0);
           model.setValueAt(note1, indice, 1);
           model.setValueAt(note2, indice, 2);
           model.setValueAt(note3, indice, 3);
           model.setValueAt(moyenne, indice,4);
        }
        }
        
    }//GEN-LAST:event_btnmodifierActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
       
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Table.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Table().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntajouter;
    private javax.swing.JButton btnmodifier;
    private javax.swing.JButton btnquiter;
    private javax.swing.JButton btnsupprimer;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel name;
    private javax.swing.JLabel note1;
    private javax.swing.JLabel note2;
    private javax.swing.JLabel note3;
    private javax.swing.JTable table;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    // End of variables declaration//GEN-END:variables
}

